services:
  postgres:
    image: postgres:17-alpine
    container_name: lifttrack-postgres

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - "5432:5432"

    volumes:
      - lifttrack-postgres-data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U lifttrack -d lifttrack"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  lifttrack-postgres-data: