spring.application.name=lift-track

spring.datasource.url=jdbc:postgresql://localhost:5432/${POSTGRES_DB:lifttrack}
spring.datasource.username=${POSTGRES_USER:lifttrack}
spring.datasource.password=${POSTGRES_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

spring.jpa.properties.hibernate.format_sql=true